### ISSUE TITLE
A dev mode to the bootstrap for easy debugging of the server

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#106]
**Is your feature request related to a problem? Please describe.**
In testing environments, we want to be able to debug the server when it happens.  By default docker permissions restrict debugging a process in the container.  You will need to modify the docker compose file and restart to enable this.  The restart might lose the repro.

**Describe the solution you'd like**
Give the user a switch to state whether symbol environment is test and allow them to setup a debugging environment.

To enable debugging add the following permissions to each service in the docker-compose file.

````
    security_opt:
    - seccomp:unconfined
    cap_add:
    - ALL
    privileged: true
````
