### ISSUE TITLE
Cap WiredTiger cache size.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#109]
**Is your feature request related to a problem? Please describe.**
When syncing current testnet, mongodb will use up to 60% of memory by default.  We need to cap this.

**Describe the solution you'd like**
Mongodb allow you to cap the cache size used the wiredTigerCacheSizeGB switch.

````
mongod --dbpath=/dbdata --bind_ip=db --wiredTigerCacheSizeGB 2
````

**Comment by fboucquez** [comment]
Have you tried a custom preset:
```
databases:
    - compose:
          mem_limit: ~
          command: 'mongod --dbpath=/dbdata --bind_ip=db --wiredTigerCacheSizeGB 2'
```
Current alpha would work. If you think it should be the new default, I'll update it.
