### ISSUE TITLE
Docker-compose logs does not show API nodes logs.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#159]
**Describe the bug**
When monitoring agent is enabled, it is added to the api-node service.  This prevent API node logs from been shown in docker logs. The monitoring agent should be its own services in the docker-compose file.

````
    api-node:
        container_name: api-node
        image: 'symbolplatform/symbol-server:gcc-0.10.1.7'
        command: >-
            bash -c "/bin/bash /symbol-commands/wait.sh ./data/broker.started && /bin/bash /symbol-commands/startServer.sh api-node DEBUG &
            /symbol-commands/agent-linux.bin --config ./userconfig/agent/agent.properties"
        stop_signal: SIGINT
        working_dir: /symbol-workdir
        restart: 'on-failure:2'
````

**Logs**
````
api-node        | 2021-02-19T05:31:48.045Z info: [ComputingPower]     computing power test started.
api-broker      | 2021-02-19 05:31:49.745747 0x00007f79b6d91700: <debug> (subscribers::BrokerMessageReaders.h@90) preparing to process 1 messages from ./data/spool/unconfirmed_transactions_change 
api-broker      | 2021-02-19 05:31:49.746121 0x00007f79b6590700: <debug> (subscribers::BrokerMessageReaders.h@90) preparing to process 1 messages from ./data/spool/block_change 
api-broker      | 2021-02-19 05:31:50.055807 0x00007f79b5d8f700: <debug> (subscribers::BrokerMessageReaders.h@90) preparing to process 2 messages from ./data/spool/state_change 
api-node        | 2021-02-19T05:31:52.063Z info: [ComputingPower]     computing power result is 6843AFD7CD9971F3DE6302C03F93AB6A5AC7AF9F1F3C35AF1A6C380EB31536BB
api-node        | 2021-02-19T05:31:52.063Z info: [ComputingPower]     computing power test ended.
api-node        | 2021-02-19T05:31:52.092Z info: [PingTask]     Performing task Ping for the following nodes:
api-node        | 2021-02-19T05:31:52.092Z info: [PingTask]     Node supernode-fernando https://54.155.40.57:7880
api-node        | 2021-02-19T05:31:52.092Z info: [PingTask]     Node 6FABC12 https://54.78.118.250:7880
api-node        | 2021-02-19T05:31:52.092Z info: [PingTask]     Node 2744649 https://34.255.180.234:7880
api-node        | 2021-02-19T05:31:52.093Z info: [PingTask]     Node A29596A https://34.254.176.96:7880
api-node        | 2021-02-19T05:31:52.093Z info: [PingTask]     Node D6C6F74 https://52.18.76.163:7880
api-node        | 2021-02-19T05:31:52.093Z info: [PingTask]     Node 354B892 https://54.155.227.155:7880
api-node        | 2021-02-19T05:31:52.093Z info: [PingTask]     Node C702EF6 https://34.245.139.48:7880
api-node        | 2021-02-19T05:31:52.093Z info: [PingTask]     Node 533D475 https://18.202.77.57:7880
api-node        | 2021-02-19T05:31:52.094Z info: [PingTask]     Node FBF2933 https://63.32.71.233:7880
api-node        | 2021-02-19T05:31:52.094Z info: [PingTask]     Node C279B77 https://54.76.4.105:7880
api-node        | 2021-02-19T05:31:52.094Z info: [PingTask]     Node FB456F5 https://34.255.196.74:7880
api-node        | 2021-02-19T05:31:52.096Z info: [PingTask]     Node F88273D https://54.194.90.253:7880
api-node        | 2021-02-19T05:31:52.097Z info: [PingTask]     Node B9790ED https://34.254.193.78:7880
api-node        | 2021-02-19T05:31:52.097Z info: [PingTask]     Node 70B1945 https://52.51.4.35:7880
api-node        | 2021-02-19T05:31:52.097Z info: [PingTask]     Node 1B2FB38 https://18.203.103.193:7880
api-node        | 2021-02-19T05:31:52.097Z info: [PingTask]     Node 4635262 https://52.30.190.244:7880
api-node        | 2021-02-19T05:31:52.098Z info: [PingTask]     Node E84A679 https://54.74.113.83:7880
api-node        | 2021-02-19T05:31:52.098Z info: [PingTask]     Node BDB6952 https://3.249.12.94:7880
api-node        | 2021-02-19T05:31:52.098Z info: [PingTask]     Node 2D38C94 https://34.245.112.102:7880
api-node        | 2021-02-19T05:31:52.098Z info: [PingTask]     Node 2F5EF50 https://3.250.185.235:7880
````
