### ISSUE TITLE
Allow custom params for genearted docker-compose's services

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-bootstrap#19]
This feature is to allow users to provide custom docker params via presets that will be added to the generated docker-compose file. 

One example would be allowing `mem_limit` to a service like the mongo db service. 

This feature could be more general. A custom preset could look like:

```
databases:
    - name: db
    - docker:
           - mem_limit: 1000000000
           - memswap_limit: 2000000000
          .... any other docker-compose service param
```

The tool would inject `mem_limit` and `memswap_limit` in the database's docker-compose service. 
The same params could be merged into any other service like peers or gateways.

The tool should probably whitelist the possible values docker accepts. 

We should also consider having top-level docker-compose customizations.
