### ISSUE TITLE
Mongodb should be configured to restart if crash.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-bootstrap#239]
**Describe the bug**
There are couple of nodes which failed due to the mongodb is down.

**To Reproduce**
To reproduce the behavior:
1. Kill the mongodb container

**Expected behavior**
To try to restart after kill

**Logs**
````
version: '2.4'
services:
    db:
        user: '1000:1000'
        environment:
            MONGO_INITDB_DATABASE: catapult
        container_name: db
        image: 'mongo:4.4.3-bionic'
        command: mongod --dbpath=/dbdata --bind_ip=db --wiredTigerCacheSizeGB 2
        stop_signal: SIGINT
        working_dir: /docker-entrypoint-initdb.d
        volumes:
            - './mongo:/docker-entrypoint-initdb.d:ro'
            - '../databases/db:/dbdata:rw'
````
