### ISSUE TITLE
Upgrade issue from 1.0.3 to 1.0.5: agent node NODE_PRIVATE_KEY is missing Error.

### ISSUE THREAD

**Issue by Drunkar** [nemtech/symbol-bootstrap#240]
**Describe the bug**
I upgraded my bootstrap from 1.0.3 to 1.0.5 and after that my agent container won't run anymore...
Agent container says "Error: Configuration could not be loaded! NODE_PRIVATE_KEY is missing." (Please see attached log.)
Should I change something in config file for supernode for 1.0.5 upgrade? Thanks

**To Reproduce**
My upgrade commands were below:

```
symbol-bootstrap stop
sudo npm install -g npm
sudo npm install -g symbol-bootstrap@latest
symbol-bootstrap config -p mainnet -a dual -c my-preset.yml --upgrade
symbol-bootstrap run -d
```

My config file (my-preset.yml) didn't changed. (I masked address and private keys to paste here)
```
beneficiaryAddress: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
transactionSelectionStrategy: maximize-fee
nodes:
        - friendlyName: Nakamoto Satoshi Node
          rewardProgram: 'supernode'
          mainPrivateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          nemesisSignerPrivateKey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          host: l.symbol-nember.tokyo
          agentUrl: https://l.symbol-nember.tokyo
          restGatewayUrl: http://l.symbol-nember.tokyo
          voting: true
          maxUnlockedAccounts: 50
          minFeeMultiplier: 100
```

**Expected behavior**
node-agent container runs successfully.

**Logs**
The result of `docker logs node-agent` is this:

```
Error: Configuration could not be loaded! NODE_PRIVATE_KEY is missing. Are you providing the right .env file, custom --config file or ENV variables?
    at Function.load (/snapshot/symbol-node-rewards/packages/agent/build/Config.js)
    at Object.<anonymous> (/snapshot/symbol-node-rewards/packages/agent/build/app.js)
    at Module._compile (pkg/prelude/bootstrap.js:1320:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1156:10)
    at Module.load (internal/modules/cjs/loader.js:984:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at internal/main/run_main_module.js:17:47
Loading custom config file 'agent.properties'...
pkg/prelude/bootstrap.js:1320
      return wrapper.apply(this.exports, args);
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS
 - Tool Version: 1.0.5
 - Docker Version: Docker version 20.10.5, build 55c4c88
 - Node Version: node v10.19.0, npm 7.11.2

**Additional context**
