### ISSUE TITLE
Preset "repeat" to allow multiple service definitions

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-bootstrap#29]
Allow "repeat" field that generates multiple configuration for a service defined. The service could be a database, node or rest. For example:

`````
nemesis:
    transactionsDirectory: '/nemesis/transactions'
    binDirectory: /data/seed
    mosaics:
        - name: 'xym'
          divisibility: 6
          duration: 0
          supply: 8998999998000000
          isTransferable: true
          isSupplyMutable: false
          isRestrictable: false
          accounts: 5
databases:
    - repeat: 10
      name: 'db-$index'
      openPort: "27017 + $index" 
nodes:
    - repeat: 20
      harvesting: true
      voting: true
      api: false
      type: peer-node
      syncsource: true
      filespooling: false
      partialtransaction: false
      name: 'peer-node-$index'
      friendlyName: 'peer-node-$index'
      host: 'peer-node-$index'
      openPort: "7900 + $index" 
      sinkType: 'Sync'
      enableSingleThreadPool: true
      addressextraction: false
      mongo: false
      zeromq: false
    - repeat: 10
      harvesting: false
      voting: false
      api: true
      type: api-node
      syncsource: false
      filespooling: true
      partialtransaction: true
      friendlyName: 'api-node-$index'
      name: 'api-node-$index'
      host: 'api-node-$index'
      brokerHost: 'api-node-broker-$index'
      openBrokerPort: "8000 + $index"
      sinkType: 'Async'
      enableSingleThreadPool: false
      addressextraction: true
      mongo: true
      zeromq: true
      databaseHost: 'db-$index'
      enableAutoSyncCleanup: false
gateways:
    - repeat: 10
      apiNodeConfigPath: '/usr/local/share/symbol/api-node-config'
      apiNodeHost: 'api-node-$index'
      apiNodeBrokerHost: 'api-node-broker-$index'
      name: 'rest-gateway'
      description: 'catapult development network'
      maxConnectionAttempts: 7
      baseRetryDelay: 750
      databaseHost: 'db-$index'
      openPort: "3000 + $index"
networkType: 152
inflation:
    starting-at-height-1: 0
    starting-at-height-10000: 0
`````

Generates 20 peers 10 API, 10 databases, and 10 rest rest gateways. Note that `$index` will be automatically resolved with the index of the given instance. 

In this example, this a brand new network where the nemesis block is generated (nemesis: section). But it could also be a set of nodes for an existing network if the seed files are provided like in the testnet preset. 

openPort = "7900 + $index"  is just to bind the external port for docker-compose if needed. Internally the server will use the default/configured ports. 

The preset can be used to fire a really big docker-compose or to just generate the configuration for all the nodes that could be potentially deployed into the cloud
