### ISSUE TITLE
Extend "link" command to announce bonded transactions when signing key is multisig account

### ISSUE THREAD

**Issue by fboucquez** [nemtech/symbol-bootstrap#31]
ATM, the new `link` command assumes that the signing harvesting account is a single account. It could happen that the user provides a custom signing account that's a multisig (or the node admin converted the singing key before linking it). 

This task is to update the `link` command to automatical detect if the signing account is multisig,  If this is the case, announce an Aggregate Bonded transaction and advice the node admin that the cosigners need to sign in the next X days.  The list of cosigner addresses could be logged/displayed on the screen. 

The way a user can provide specific node keys is with a custom preset:

````
nodes: 
#  First node specific keys (single opted in account)
  - signingPrivateKey: AAAAA282dd025e1ab24ac7d5efbd8b7b5cf3036e16cbee8c62ec5d31a221f
    vrfPrivateKey: CCCCeef282dd025e1ab24ac7d5efbd8b7b5cf3036e16cbee8c62ec5d31a221f
    votingPrivateKey: BBBBBeef282dd025e1ab24ac7d5efbd8b7b5cf3036e16cbee8c62ec5d31a221f (No needed for haversting, just example of providing a specific voting key)
#  Second node specific keys (multisig opted in account)
  - signingPrivateKey: DDDDDeef282dd025e1ab24ac7d5efbd8b7b5cf3036e16cbee8c62ec5d31a221f
````

(if a key is not provided, it will be generated and stored in the addresses.yml)

The best use case of providing a specific key is for nis1 opted in nodes. The signing and vrf keys are the ones generated the opt-in process and already included in the block 1. This new multisig link could be used to workaround the lack of opt in vrf mutlisig transactions. The signing is migrated multisig account, the vrf is a generated new one. The new link command links both. Mutlisig harvest account can start harvesting quickly by just calling the link command after booting the node.
